config/routes.rb
Rails.application.routes.draw do
  root "short_url#index"
  resources :short_url

  get ':unique_string', :to => 'short_url#redirect'

end

app/models/short_url_list.rb
class ShortUrlList < ActiveRecord::Base

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/short_url_controller.rb
class ShortUrlController < ApplicationController
  def index
    @short_url = ShortUrlList.new
  end

  def create
    @redirect = params.require(:short_url_list).permit(:redirect)
    # 查詢是不是有建立過相同的短網址 若有直接顯示
    # @exist_redirect  = ShortUrlList.where('redirect = ?' , @redirect[:redirect]).take(1)
    @exist_redirect = ShortUrlList.find_by(redirect: @redirect[:redirect])
    if (@exist_redirect == nil)
      # Creat unique_string and Insert redirect to url
      @create_unique_string = 1
      while @create_unique_string != nil do
        unique_string = SecureRandom.hex(5)
        @create_unique_string = ShortUrlList.find_by(unique_string: unique_string)
      end

      @exist_redirect = ShortUrlList.create(:unique_string => unique_string, :redirect => @redirect[:redirect], :count => 0)
    end


  end

  def redirect
    @hash = params.permit(:unique_string)
    @exist_redirect = ShortUrlList.find_by(unique_string: @hash[:unique_string])
    if @exist_redirect != nil
      @exist_redirect.update(count: @exist_redirect.count+1)
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/short_url_helper.rb
module ShortUrlHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>ShortUrl</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/short_url/create.html.erb
網址：<%= link_to request.host_with_port + '/' + @exist_redirect.unique_string , "http://"+request.host_with_port + '/' + @exist_redirect.unique_string %>

app/views/short_url/index.html.erb
<div class="panel panel-default devise-bs">
  <div class="panel-heading">
    <h4>產生短網址</h4>
  </div>
  <div class="panel-body">
    <%= form_for @short_url ,  :url => short_url_index_path() , :method =>'post'  do |f| %>
        <div class="form-group">
          <%= f.label :redirect_to %>
          <%= f.url_field :redirect , autofocus: true, class: "form-control" %>
        </div>
        <%= f.submit t('.sign_up', :default => "產生短網址"), class: "btn btn-primary" %>
    <% end %>
  </div>
</div>

app/views/short_url/redirect.html.erb
<% if @exist_redirect != nil %>
    第<%= @exist_redirect.count %>次轉址到<%= link_to @exist_redirect.redirect %><br/>
    5秒後自動轉跳
    <script>window.setTimeout("location.href='<%= @exist_redirect.redirect %>'", 5000);</script>
<% else %>
    阿！我不認識這個短網址！<%= link_to "創立一個短網址" ,  short_url_index_path() %>吧！
<% end %>